config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }, skip: :registrations

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  namespace :admin do
    resources :games
    resources :game_developers
  end

  root 'games#index'

  resources :games, only: [:index, :show, :new, :create] do
    member do
      get 'upvote'
      get 'unupvote'
    end
    resources :videos, only: [:create]
    resources :comments, only: [:create]
  end

  resources :users do
    get :autocomplete_user_name, :on => :collection
  end

end

app/models/game_developer.rb
class GameDeveloper < ActiveRecord::Base
  validates :title, presence: true
  validates :location, presence: true

  has_many :games

  mount_uploader :thumbnail, ThumbnailUploader
end

app/controllers/admin/game_developers_controller.rb
module Admin
  class GameDevelopersController < ApplicationController
    load_and_authorize_resource

    def new
    end

    def edit
    end

    def create
      if @game_developer.save
        redirect_to admin_game_developers_path
      else
        render :new
      end
    end

    def update
      if @game_developer.update_attributes(game_developer_params)
        redirect_to admin_game_developers_path
      else
        render :edit
      end
    end

    def destroy
      @game_developer.destroy
      redirect_to admin_game_developers_path, notice: "Destroyed game developer"
    end

    private
    def game_developer_params
      params.require(:game_developer).permit(:title, :location, :thumbnail)
    end
  end
end

app/views/admin/game_developers/_form.html.erb
<%= form_for([:admin, @game_developer]) do |f| %>
  <% if @game_developer.errors.any? %>
    <div id="form_errors">
      <h2>Errors while saving:</h2>
      <ul>
      <% @game_developer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb3">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'field-light block full-width' %>
  </div>

  <div class="mb3">
    <%= f.label :location %><br>
    <%= f.text_field :location, class: 'field-light block full-width' %>
  </div>

  <div class="clearfix mb3 mxn2">
    <div class="col col-6 px2">
      <%= f.label :thumbnail %><br>
      <%= f.file_field :thumbnail %>
    </div>
  </div>

  <div class="right-align">
    <%= f.button 'Submit Game Developer', class: 'button-blue' %>
  </div>
<% end %>

app/views/admin/game_developers/edit.html.erb
<div class="container py3">
  <div class="bg-white col-6 mx-auto p3">
    <h1 class="mt0 mb1">Add a game developer</h1>
    <%= render partial: 'admin/game_developers/form' %>
  </div>
</div>

app/views/admin/game_developers/index.html.erb
<div class="container py3">
  <%= link_to 'Manage Games', admin_games_path %> | <%= link_to 'Create Game Developer', new_admin_game_developer_path %>
  <table class="table-light">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Location</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @game_developers.each do |dev| %>
        <tr>
          <td>
            <a class="light-gray" href="<%= edit_admin_game_developer_path(dev) %>">Edit</a>
          </td>
          <td><%= dev.title %></td>
          <td>
            <%= dev.location %>
          </td>
          <td>
            <%= link_to [:admin, dev], method: :delete, data: { confirm: "Are you sure?" }, class: 'red' do %>
              Delete
            <% end %>
          </td>
       </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/game_developers/new.html.erb
<div class="container py3">
  <div class="bg-white col-6 mx-auto p3">
    <h1 class="mt0 mb1">Add a game developer</h1>
    <%= render partial: 'admin/game_developers/form' %>
  </div>
</div>