config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }, skip: :registrations

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  namespace :admin do
    resources :games
    resources :game_developers
  end

  root 'games#index'

  resources :games, only: [:index, :show, :new, :create] do
    member do
      get 'upvote'
      get 'unupvote'
    end
    resources :videos, only: [:create]
    resources :comments, only: [:create]
  end

  resources :users do
    get :autocomplete_user_name, :on => :collection
  end

end

app/models/game.rb
class Game < ActiveRecord::Base
  STATUS_TYPES = ["released", 0], ["beta",1]

  validates :title, :link, presence: true

  has_many :videos
  has_many :comments
  has_many :game_platforms, dependent: :destroy
  has_many :platforms, through: :game_platforms
  belongs_to :user
  belongs_to :game_developer

  accepts_nested_attributes_for :game_platforms, reject_if: :all_blank, allow_destroy: true

  default_scope -> { where(deleted_at: nil) }

  scope :unscheduled, -> { where(scheduled_at: nil) }
  scope :scheduled, -> { where('scheduled_at <= ?', Date.today) }
  scope :display_order, -> { order(:cached_votes_up).reverse_order }
  scope :with_platform, -> (name) { joins(:platforms).where(platforms: { name: name }) }

  acts_as_votable

  mount_uploader :thumbnail, ThumbnailUploader

  def soft_destroy
    touch(:deleted_at)
    freeze
  end

  def find_related_platforms
    Game
      .joins(:platforms)
      .where(platforms: { id: platforms.map(&:id) })
      .where.not(games: { id: id })
  end
end

app/controllers/admin/games_controller.rb
module Admin
  class GamesController < ApplicationController
    load_and_authorize_resource

    before_action :set_game_developers, only: [:edit, :update]

    def index
      @games = @games.order(:scheduled_at)
    end

    def show
      @video = @game.videos.new
    end

    def edit
    end

    def update
      scheduled_before = @game.scheduled_at?
      if @game.update_attributes(game_params)
        if !scheduled_before && @game.reload.scheduled_at?
          UserMailer.game_scheduled(@game).deliver_later
        end
        redirect_to admin_games_path
      else
        render :edit
      end
    end

    def destroy
      @game.soft_destroy
      redirect_to admin_games_path, notice: "Destroyed game"
    end

    private
    def set_game_developers
      @game_developers = GameDeveloper.order(:title).all.pluck(:title, :id)
    end

    def game_params
      params.require(:game).permit(
        :title,
        :thumbnail,
        :description,
        :extended_description,
        :status,
        :link,
        :scheduled_at,
        :game_developer_id,
        game_platforms_attributes: [
          :id,
          :platform_id,
          :url,
          :_destroy
        ]
      )
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  load_and_authorize_resource
  respond_to :html, :js

  def index
    @current_week = params[:week].present? ? Date.parse(params[:week]) : Date.today.beginning_of_week
    @last_week = @current_week - 7.days
    @next_week = @current_week + 7.days

    @platforms = Platform.all

    @games = @games.with_platform(params[:platform]) if params[:platform].present?

    @weeks = @games.includes(:user, :platforms).where("scheduled_at >= ? and scheduled_at < ?", @current_week, @next_week).scheduled.display_order.group_by do |game|
      params[:view] == "weekly" ? game.scheduled_at.beginning_of_week : game.scheduled_at
    end.sort.reverse
  end

  def new
  end

  def create
    @game.user = current_user
    if @game.save
      flash[:notice] = "Thanks for submitting, your submission is under review. You'll be emailed if and when your submission is scheduled"
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @video = Video.new
    @related_games = @game.find_related_platforms.scheduled.first(3)
    @comments = @game.comments.where(parent_id: nil).preload(:user, children: :user).order('updated_at desc')
    flash.now[:notice] = "This game is under review." unless @game.scheduled_at?
  end

  def upvote
    if @game.scheduled_at?
      @game.upvote_by(current_user)
    else
      flash[:error] = "Sorry. You can't vote on unpublished games"
    end

    respond_to do |format|
      format.js do
        @game.scheduled_at? ? render(:vote) : render(js: "window.location = '#{game_path(@game)}'")
      end
      format.html { redirect_to :back }
    end
  end

  def unupvote
    @game.unvote_by(current_user)
    respond_to do |format|
      format.js { render :vote }
      format.html {redirect_to :back}
    end
  end

  def upload
    uploaded_io = params[:game][:thumbnail]
    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end
  end

  private
  def game_params
    params.require(:game).permit(
      :title,
      :thumbnail,
      :description,
      :extended_description,
      :status,
      :link,
      game_platforms_attributes: [
        :id,
        :platform_id,
        :url,
        :_destroy
      ]
    )
  end
end

app/helpers/game_helper.rb
module GameHelper
  def game_platforms_list(game)
    game.platforms.map(&:name).join(", ")
  end
end

app/views/admin/games/_form.html.erb
<%= form_for([:admin, game]) do |f| %>
  <% if game.errors.any? %>
    <div id="form_errors">
      <h2>Errors while saving:</h2>
      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb3">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'field-light block full-width' %>
  </div>

  <div class="mb3">
    <%= f.label :link, 'URL' %><br>
    <%= f.text_field :link, class: 'field-light block full-width' %>
  </div>

  <div class="mb3">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'field-light block full-width', rows: 2 %>
  </div>

  <div class="mb3">
    <%= f.label :extended_description %><br>
    <%= f.text_area :extended_description, class: 'field-light block full-width', rows: 2 %>
  </div>

  <div class="clearfix mb3 mxn2">
    <div class="col col-6 px2">
      <%= f.label :thumbnail %><br>
      <%= f.file_field :thumbnail %>
    </div>
  </div>

  <div class="mb3">
    <%= f.label :game_developer %><br>
    <%= f.select :game_developer_id, @game_developers, include_blank: true %>
  </div>

  <fieldset class="mb3 game_platforms">
    <legend>Platforms</legend>
    <%= f.fields_for :game_platforms do |game_platforms| %>
      <%= render 'game_platform_fields', f: game_platforms %>
    <% end %>
  </fieldset>

  <div class="mb3">
    <%= link_to_add_association(
      'Add platform',
      f, :game_platforms,
      class: 'light-gray',
      data: {
        association_insertion_node: '.game_platforms',
        association_insertion_method: 'append'
      }
    ) %>
  </div>

  <div class="right-align">
    <%= f.button 'Submit Game', class: 'button-blue' %>
  </div>
<% end %>

app/views/admin/games/_game_platform_fields.html.erb
<div class="mb3 nested-fields">
  <%= f.hidden_field :id %>
  <div>
    <%= f.label :platform_id %>
    <br />
    <%= f.collection_select(:platform_id, Platform.all, :id, :name) %>
  </div>
  <div>
    <%= f.label :url %>
    <br />
    <%= f.text_field :url %>
  </div>

  <div>
    <%= link_to_remove_association 'Remove platform', f, class: 'red' %>
  </div>
</div>

app/views/admin/games/edit.html.erb
<div class="container py3">
  <div class="bg-white col-6 mx-auto p3">
    <h1 class="mt0 mb1">Add a game</h1>
    <p class="mid-gray mb3">Know a game that you think is awesome? Submit it to share it with everybody. The game must be playable.</p>
    <%= render partial: 'admin/games/form', locals: { game: @game } %>
  </div>
</div>

app/views/admin/games/index.html.erb
<div class="container py3">
  <%= link_to 'Manage Game Developers', admin_game_developers_path %>
  <table class="table-light">
    <thead>
      <tr>
        <th colspan="2"></th>
        <th>Platform</th>
        <th>Votes</th>
        <th>Scheduled</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @games.each do |game| %>
        <tr>
          <td><a class="light-gray" href="<%= edit_admin_game_path(game) %>">Edit</a></td>
          <td>
            <%= link_to game.title, game %>
            <p class="mid-gray mb0"><%= game.link %></p>
          </td>
          <td><%= game_platforms_list(game) %></td>
          <td>up: <%= game.cached_votes_up %> / down: <%= game.cached_votes_down %></td>
          <td>
            <% if game.scheduled_at? %>
              <%= format_date(game.scheduled_at) %>
            <% else %>
              <%= form_for(game, url: [:admin, game]) do |f| %>
                <%= f.date_field :scheduled_at, min: Date.today, value: Date.today, class: 'field-light py1 mb0' %>
                <%= f.button 'Save', class: 'button-blue-outline' %>
              <% end %>
            <% end %>
          </td>
          <td>
            <%= link_to [:admin, game], method: :delete, class: 'red' do %>
              Delete
            <% end %>
          </td>
       </tr>
      <% end %>
    </tbody>
  </table>
</div>