config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }, skip: :registrations

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  namespace :admin do
    resources :games
    resources :game_developers
  end

  root 'games#index'

  resources :games, only: [:index, :show, :new, :create] do
    member do
      get 'upvote'
      get 'unupvote'
    end
    resources :videos, only: [:create]
    resources :comments, only: [:create]
  end

  resources :users do
    get :autocomplete_user_name, :on => :collection
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  ROLES = ["admin"]

  # enable reverse functionality for vots
  acts_as_voter

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :confirmable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # TODO Can a user have many identities? What if he connects both FB, TW etc profiles?
  has_many :identities, dependent: :destroy
  has_many :comments
  has_many :games

  validates :email,
                format: { without: TEMP_EMAIL_REGEX, on: :update},
                presence: true,
                uniqueness: true

  validates :username,
                format: { with: /\A[a-zA-Z0-9\-\_]+\Z/ },
                presence: true,
                uniqueness: true

  def to_param
    username
  end

  def is_admin?
    self.role == "admin"
  end

  def self.find_for_mention mention
    find_mention = mention.dup
    find_mention.strip!
    find_mention.slice!("@")
    find_by(username: find_mention)
  end

  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?

        user = User.new(
          name: auth.extra.raw_info.name,
          twitter_handle: auth.info.nickname,
          username: create_username_from(auth.info.nickname || auth.uid),
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20],
          avatar_url: auth.info.image
        )
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def self.create_username_from name
    username = n = ""
    loop do
      username = name.parameterize + n.to_s
      n = n.to_i + 1
      break unless User.exists?(username: username)
    end
    username
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource find_by: :username, :except => :autocomplete_user_name

  # GET /users/:id.:format
  def show
    # authorize! :read, @user
  end

  # GET /users/:id/edit
  def edit
  end

  # PATCH/PUT /users/:id.:format
  def update
    # authorize! :update, @user
    respond_to do |format|
      if @user.update(user_params)
        sign_in(@user == current_user ? @user : current_user, :bypass => true)
        format.html { redirect_to @user, notice: 'Your profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET/PATCH /users/:id/finish_signup
  def finish_signup
    #authorize! :update, @user
    @user.email = nil if !@user.email_verified?
    if request.patch? && params[:user]
      if @user.update(user_params)
        sign_in(@user == current_user ? @user : current_user, :bypass => true)
        flash[:notice] = ""
        redirect_to root_url
      else
        # If user already exist with that e-mail tell the user that
        # TODO Improve this flow. What should actually happen when the following happens:
        # 1. The user signs-up with Twitter, goes about his business and signs-out
        # 2. Later returns to our site but this time clicks sign-in with Facebook. He will then not be recognized
        #    hence flashed the usual sign-up procedure.
        # 3. If he then enters the e-mail he used to sign-up with in step 1, what should actually happen?
        if User.find_by_email(user_params[:email])
          flash[:notice] = "A user already exist with that e-mail."
        end
        @show_errors = true
      end
    end
  end

  # DELETE /users/:id.:format
  def destroy
    # authorize! :delete, @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

  def autocomplete_user_name
    users = User.select([:username], [:id], [:avatar_url]).where("username LIKE ?", "%#{params[:term]}%")
    result = users.collect do |t|
      { id: t.id, name: t.username, avatar: t.avatar_url, type: 'contact' }
    end
    render json: result
  end

  private
    def set_user
      @user = current_user
      unless @user
        flash[:error] = "Something went wrong while signup. Please try again."
        redirect_to root_path
      end
    end

    # This checks which parameters are permitted for change. Remember to update it if new parameters are introduced
    def user_params
      params.require(:user).permit(:name,:email,:password,:password_confirmation,:occupation, :receive_newsletter, :username, :email_notifications)
    end
end

app/helpers/user_helper.rb
module UserHelper
  def avatar_for(user, size)
    return unless user
    avatar_url = if user.avatar_url.nil?
      avatar_path = Digest::MD5.hexdigest(user.email.downcase)
      if size == 'small'
        "https://gravatar.com/avatar/#{avatar_path}.png?s=48&d=monsterid"
      elsif size == 'large'
        "https://gravatar.com/avatar/#{avatar_path}.png?s=130&d=monsterid"
      end
    else
      if size == 'small'
        user.avatar_url
      elsif size == 'large'
        user.avatar_url.sub! 'normal', '400x400'
      end
    end

    link_to user, class: "block avatar" do
      if size == 'small'
        image_tag avatar_url, class: "block", width: "30", height: "30"
      elsif size == 'large'
        image_tag avatar_url, class: "block", width: "130", height: "130"
      end
    end
  end
end

app/views/users/_form.html.erb
  <%= form_for(@user, :html => { role: 'form'}) do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <% @user.errors.full_messages.each do |msg| %>
          <%= msg %><br>
        <% end %>
      </div>
    <% end %>
    <div class="form-group">

      <div class="clearfix mb2">
        <%= f.label :username, class: 'block col col-3' %>
        <%= f.text_field :username, :autofocus => true, class: 'block field-light col col-9' %>
      </div>

      <div class="clearfix mb2">
        <%= f.label :email, class: 'block col col-3' %>
        <% if @user.email %>
          <%= f.text_field :email, :value => @user.email, class: 'block field-light col col-9' %>
        <% else %>
          <%= f.text_field :email, :value => '', class: 'block field-light col col-9', placeholder: 'Example: email@me.com' %>
        <% end %>
      </div>

      <div class="clearfix mb2">
        <%= f.label :occupation, class: 'block col col-3' %>
        <%= f.text_field :occupation, :value => @user.occupation, class: 'block field-light col col-9', placeholder: 'Occupation' %>
      </div>

      <div class="clearfix mb2">
        <div class="controls">
          <%= f.check_box :email_notifications %> Email Notifications
          <p class="help-block">Recieve emails when you are mentioned in comments.</p>
        </div>

      </div>

    <div class="form-group">
      <div class="controls">
        <%= f.check_box :receive_newsletter %> Signup For Our Newsletter
        <p class="help-block">Get new games in your inbox every week. Unsubscribe at any time.</p>
      </div>

    <div class="actions clearfix">
      <%= f.submit 'Update', :class => 'button button-blue right px4' %>
    </div>
  <% end %>

app/views/users/_game.html.erb
<div class="clearfix game-block">

<div class="bg-white col clearfix relative game">
  <div class="col column info">

    <h4 class="mt0">
      <a class="dark-gray title" href="<%= game_path(game) %>"><%= game.title %></a>
    </h4>
    <p class="mb0 caption"><%= truncate(game.description, length: 120) %></p>

    <footer class="game-meta col-7">        
        <ul class="list-reset platform-list">
            <% game.platform_list.each do |platform| %>
              <li><%= platform %></li>
            <% end %>
          </ul>

      <div class="clearfix game-posted">
        <div class="left">
          <p class="mb0 posted">POSTED</p>
          <p>@<%= game.user.username %></p>
        </div>
        <div class="left ml1">
          <%= avatar_for(game.user, 'small') %>
        </div>

      </div>
    </footer>

    



  </div>

  <div class="col image" style="background-image:url(<%= image_path(game.thumbnail) %>);background-size:cover;background-position:center;height:10em"></div>

</div>

</div>

app/views/users/_nav.html.erb
<div class="image">
	<%= avatar_for @user, 'large' %>
</div>
<h3 class="user mt0">@<%= @user.username %></h3>
<p class="occupation light-gray"><%= @user.occupation %></p>

<a href="http://twitter.com/<%= @user.twitter_handle %>" class="mb3 block">
	<img src="/twitter.png" width="21" height="17">
</a>

app/views/users/edit.html.erb
  <section class="container clearfix mt2">
  	<div class="col bg-white user-meta">
  		<%= render 'users/nav' %> 
  	</div>
  	<div class="col user-edit">
  		<div class="profile-settings bg-white p3">
	  		<p class="mb1">Profile Settings</p>
	  		<p class="light-gray update">Update your username, email and password</p>

	  		<%= render "form" %>
	  	</div>
  		
  	</div>
  </section>

app/views/users/finish_signup.html.erb
<div id="add-email" class="container">
  <h1>Add Email</h1>
  <%= form_for(@user, :as => 'user', :url => finish_signup_path(@user), :html => { role: 'form'}) do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <% @user.errors.full_messages.each do |msg| %>
          <%= msg %><br>
        <% end %>
      </div>
    <% end %>
    <div class="form-group">

      <%= f.label :username %>
      <div class="controls">
        <%= f.text_field :username, :autofocus => true, class: '' %>

        <p class="help-block">Username should only contain letters, numbers, and "-", "_".</p>
      </div>

      <%= f.label :email %>
      <div class="controls">
        <% if @user.email %>
          <%= f.text_field :email, :value => @user.email, class: '' %>
        <% else %>
          <%= f.text_field :email, :value => '', class: '', placeholder: 'Example: email@me.com' %>
        <% end %>

        <p class="help-block">Please confirm your email address. No spam.</p>
      </div>

    <div class="form-group">
      <div class="controls">
        <%= f.check_box :receive_newsletter %> Signup For Our Newsletter
        <p class="help-block">Get new games in your inbox every week. Unsubscribe at any time.</p>
      </div>

      <div class="form-group">
        <%= f.label :occupation %>
        <div class="controls">
          <%= f.text_field :occupation, :value => @user.occupation, class: '', placeholder: 'Occupation' %>
        </div>
    </div>
    <div class="actions">
      <%= f.submit 'Continue', :class => 'btn btn-primary' %>
    </div>
  <% end %>
  <!-- Added for pure building convenience, probably shouldn't be here -->
  <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
</div>

app/views/users/show.html.erb
<% voted_games = @user.find_voted_items %>
<section class="container clearfix mt2">
	<div class="col bg-white user-meta">
		<%= render 'users/nav' %> 

		<% if @user == current_user %>
			<%= link_to "Edit Profile", edit_user_path(current_user), class: 'button button-blue' %>
		<% end %>
	</div>
	<div class="col user-votes">
		<section class="filter-bar bg-white mb2">
			<ul class="list-reset clearfix m0 py2">
				<li><a class="p2 link selected" href="#">Upvoted</a></li>
			</ul>
		</section>

		<% voted_games.each do |game| %>
			<%= render 'users/game', game: game %>
		<% end %>
	</div>
</section>